//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionsByAsset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionsByAsset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="a010" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a014" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a015" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a017" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a019" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a020" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a023" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a024" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a029" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a049" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a070" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a074" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a075" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a076" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a077" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a090" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a100" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a103" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a104" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a110" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a113" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a300" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a303" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a30X" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a310" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a320" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a324" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a330" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a334" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a340" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a350" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a360" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a374" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a400" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a403" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a404" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a40W" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a40X" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a40Z" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a410" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a413" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a420" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a423" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a430" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a433" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a434" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a440" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a443" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a450" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a453" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a454" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a460" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a463" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a500" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a501" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a502" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a503" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a504" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a510" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a511" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a512" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a520" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a521" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a522" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a800" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a980" type="{}DateOrTimedDateUnion"/>
 *         &lt;element name="a981" type="{}DateOrTimedDateUnion"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionsByAsset", propOrder = {
    "a010SAndA014SAndA015S"
})
public class ActionsByAsset {

    @XmlElementRefs({
        @XmlElementRef(name = "a360", type = JAXBElement.class),
        @XmlElementRef(name = "a334", type = JAXBElement.class),
        @XmlElementRef(name = "a501", type = JAXBElement.class),
        @XmlElementRef(name = "a512", type = JAXBElement.class),
        @XmlElementRef(name = "a074", type = JAXBElement.class),
        @XmlElementRef(name = "a015", type = JAXBElement.class),
        @XmlElementRef(name = "a40W", type = JAXBElement.class),
        @XmlElementRef(name = "a463", type = JAXBElement.class),
        @XmlElementRef(name = "a503", type = JAXBElement.class),
        @XmlElementRef(name = "a300", type = JAXBElement.class),
        @XmlElementRef(name = "a340", type = JAXBElement.class),
        @XmlElementRef(name = "a443", type = JAXBElement.class),
        @XmlElementRef(name = "a320", type = JAXBElement.class),
        @XmlElementRef(name = "a413", type = JAXBElement.class),
        @XmlElementRef(name = "a30X", type = JAXBElement.class),
        @XmlElementRef(name = "a410", type = JAXBElement.class),
        @XmlElementRef(name = "a403", type = JAXBElement.class),
        @XmlElementRef(name = "a430", type = JAXBElement.class),
        @XmlElementRef(name = "a522", type = JAXBElement.class),
        @XmlElementRef(name = "a310", type = JAXBElement.class),
        @XmlElementRef(name = "a423", type = JAXBElement.class),
        @XmlElementRef(name = "a075", type = JAXBElement.class),
        @XmlElementRef(name = "a433", type = JAXBElement.class),
        @XmlElementRef(name = "a450", type = JAXBElement.class),
        @XmlElementRef(name = "a520", type = JAXBElement.class),
        @XmlElementRef(name = "a324", type = JAXBElement.class),
        @XmlElementRef(name = "a980", type = JAXBElement.class),
        @XmlElementRef(name = "a023", type = JAXBElement.class),
        @XmlElementRef(name = "a40Z", type = JAXBElement.class),
        @XmlElementRef(name = "a076", type = JAXBElement.class),
        @XmlElementRef(name = "a017", type = JAXBElement.class),
        @XmlElementRef(name = "a981", type = JAXBElement.class),
        @XmlElementRef(name = "a800", type = JAXBElement.class),
        @XmlElementRef(name = "a020", type = JAXBElement.class),
        @XmlElementRef(name = "a40X", type = JAXBElement.class),
        @XmlElementRef(name = "a330", type = JAXBElement.class),
        @XmlElementRef(name = "a014", type = JAXBElement.class),
        @XmlElementRef(name = "a090", type = JAXBElement.class),
        @XmlElementRef(name = "a434", type = JAXBElement.class),
        @XmlElementRef(name = "a400", type = JAXBElement.class),
        @XmlElementRef(name = "a104", type = JAXBElement.class),
        @XmlElementRef(name = "a511", type = JAXBElement.class),
        @XmlElementRef(name = "a303", type = JAXBElement.class),
        @XmlElementRef(name = "a500", type = JAXBElement.class),
        @XmlElementRef(name = "a521", type = JAXBElement.class),
        @XmlElementRef(name = "a103", type = JAXBElement.class),
        @XmlElementRef(name = "a049", type = JAXBElement.class),
        @XmlElementRef(name = "a019", type = JAXBElement.class),
        @XmlElementRef(name = "a453", type = JAXBElement.class),
        @XmlElementRef(name = "a350", type = JAXBElement.class),
        @XmlElementRef(name = "a374", type = JAXBElement.class),
        @XmlElementRef(name = "a460", type = JAXBElement.class),
        @XmlElementRef(name = "a454", type = JAXBElement.class),
        @XmlElementRef(name = "a504", type = JAXBElement.class),
        @XmlElementRef(name = "a113", type = JAXBElement.class),
        @XmlElementRef(name = "a440", type = JAXBElement.class),
        @XmlElementRef(name = "a502", type = JAXBElement.class),
        @XmlElementRef(name = "a070", type = JAXBElement.class),
        @XmlElementRef(name = "a029", type = JAXBElement.class),
        @XmlElementRef(name = "a420", type = JAXBElement.class),
        @XmlElementRef(name = "a510", type = JAXBElement.class),
        @XmlElementRef(name = "a024", type = JAXBElement.class),
        @XmlElementRef(name = "a077", type = JAXBElement.class),
        @XmlElementRef(name = "a110", type = JAXBElement.class),
        @XmlElementRef(name = "a404", type = JAXBElement.class),
        @XmlElementRef(name = "a100", type = JAXBElement.class),
        @XmlElementRef(name = "a010", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> a010SAndA014SAndA015S;

    /**
     * Gets the value of the a010SAndA014SAndA015S property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the a010SAndA014SAndA015S property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getA010SAndA014SAndA015S().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getA010SAndA014SAndA015S() {
        if (a010SAndA014SAndA015S == null) {
            a010SAndA014SAndA015S = new ArrayList<JAXBElement<String>>();
        }
        return this.a010SAndA014SAndA015S;
    }

}
