//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Cam-Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Cam-Item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Parent-Type-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Designated-Parent-Asset-Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Child-Type-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Child-Asset-Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Optional-Ind" type="{}tfIndicator"/>
 *         &lt;element name="Last-Updated-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Cam-Item", propOrder = {
    "parentTypeId",
    "designatedParentAssetCode",
    "childTypeId",
    "childAssetCode",
    "optionalInd",
    "lastUpdatedDate"
})
public class CamItem {

    @XmlElement(name = "Parent-Type-Id", required = true)
    protected BigInteger parentTypeId;
    @XmlElement(name = "Designated-Parent-Asset-Code", required = true)
    protected String designatedParentAssetCode;
    @XmlElement(name = "Child-Type-Id", required = true)
    protected BigInteger childTypeId;
    @XmlElement(name = "Child-Asset-Code", required = true)
    protected String childAssetCode;
    @XmlElement(name = "Optional-Ind", required = true)
    protected TfIndicator optionalInd;
    @XmlElement(name = "Last-Updated-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdatedDate;

    /**
     * Gets the value of the parentTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentTypeId() {
        return parentTypeId;
    }

    /**
     * Sets the value of the parentTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentTypeId(BigInteger value) {
        this.parentTypeId = value;
    }

    /**
     * Gets the value of the designatedParentAssetCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignatedParentAssetCode() {
        return designatedParentAssetCode;
    }

    /**
     * Sets the value of the designatedParentAssetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignatedParentAssetCode(String value) {
        this.designatedParentAssetCode = value;
    }

    /**
     * Gets the value of the childTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildTypeId() {
        return childTypeId;
    }

    /**
     * Sets the value of the childTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildTypeId(BigInteger value) {
        this.childTypeId = value;
    }

    /**
     * Gets the value of the childAssetCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildAssetCode() {
        return childAssetCode;
    }

    /**
     * Sets the value of the childAssetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildAssetCode(String value) {
        this.childAssetCode = value;
    }

    /**
     * Gets the value of the optionalInd property.
     * 
     * @return
     *     possible object is
     *     {@link TfIndicator }
     *     
     */
    public TfIndicator getOptionalInd() {
        return optionalInd;
    }

    /**
     * Sets the value of the optionalInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TfIndicator }
     *     
     */
    public void setOptionalInd(TfIndicator value) {
        this.optionalInd = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

}
