//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Component complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Component">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Label-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Comp-Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comp-Type-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Active-Status-Code" type="{}activeStatusCode"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sort-Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Subtitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Parental-Advisory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="Upc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="Child-Items-Count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *             &lt;element name="Cover-Art" type="{}tfIndicator"/>
 *             &lt;element name="Single" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Short-Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Season" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Imprint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Coverage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Table-Of-Contents" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="Isrc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;element name="Item-Number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;choice>
 *               &lt;sequence>
 *                 &lt;element name="Disk-Number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *               &lt;/sequence>
 *               &lt;sequence>
 *                 &lt;element name="Audio-Languages" type="{}Languages" minOccurs="0"/>
 *                 &lt;element name="Subtitle-Languages" type="{}Languages" minOccurs="0"/>
 *               &lt;/sequence>
 *             &lt;/choice>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Amg-Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Muze-Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Exclusive-Ind" type="{}tfIndicator"/>
 *         &lt;element name="Special-Codes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Created-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Last-Updated-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Component", propOrder = {
    "id",
    "labelId",
    "compCode",
    "compTypeId",
    "activeStatusCode",
    "title",
    "sortTitle",
    "subtitle",
    "duration",
    "parentalAdvisory",
    "isrc",
    "itemNumber",
    "upc",
    "childItemsCount",
    "coverArt",
    "single",
    "shortDescription",
    "description",
    "audioLanguages",
    "subtitleLanguages",
    "diskNumber",
    "season",
    "imprint",
    "edition",
    "coverage",
    "tableOfContents",
    "amgId",
    "muzeId",
    "exclusiveInd",
    "specialCodes",
    "createdDate",
    "lastUpdatedDate"
})
public class Component {

    @XmlElement(name = "Id", required = true)
    protected BigInteger id;
    @XmlElement(name = "Label-Id", required = true)
    protected BigInteger labelId;
    @XmlElement(name = "Comp-Code", required = true)
    protected String compCode;
    @XmlElement(name = "Comp-Type-Id", required = true)
    protected BigInteger compTypeId;
    @XmlElement(name = "Active-Status-Code", required = true)
    protected ActiveStatusCode activeStatusCode;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Sort-Title")
    protected String sortTitle;
    @XmlElement(name = "Subtitle")
    protected String subtitle;
    @XmlElement(name = "Duration", required = true)
    protected String duration;
    @XmlElement(name = "Parental-Advisory", required = true)
    protected String parentalAdvisory;
    @XmlElement(name = "Isrc")
    protected String isrc;
    @XmlElement(name = "Item-Number")
    protected BigInteger itemNumber;
    @XmlElement(name = "Upc")
    protected String upc;
    @XmlElement(name = "Child-Items-Count")
    protected BigInteger childItemsCount;
    @XmlElement(name = "Cover-Art")
    protected TfIndicator coverArt;
    @XmlElement(name = "Single")
    protected String single;
    @XmlElement(name = "Short-Description")
    protected String shortDescription;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Audio-Languages")
    protected Languages audioLanguages;
    @XmlElement(name = "Subtitle-Languages")
    protected Languages subtitleLanguages;
    @XmlElement(name = "Disk-Number")
    protected BigInteger diskNumber;
    @XmlElement(name = "Season")
    protected String season;
    @XmlElement(name = "Imprint")
    protected String imprint;
    @XmlElement(name = "Edition")
    protected String edition;
    @XmlElement(name = "Coverage")
    protected String coverage;
    @XmlElement(name = "Table-Of-Contents")
    protected String tableOfContents;
    @XmlElement(name = "Amg-Id")
    protected String amgId;
    @XmlElement(name = "Muze-Id")
    protected String muzeId;
    @XmlElement(name = "Exclusive-Ind", required = true)
    protected TfIndicator exclusiveInd;
    @XmlElement(name = "Special-Codes")
    protected String specialCodes;
    @XmlElement(name = "Created-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "Last-Updated-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdatedDate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the labelId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLabelId() {
        return labelId;
    }

    /**
     * Sets the value of the labelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLabelId(BigInteger value) {
        this.labelId = value;
    }

    /**
     * Gets the value of the compCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompCode() {
        return compCode;
    }

    /**
     * Sets the value of the compCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompCode(String value) {
        this.compCode = value;
    }

    /**
     * Gets the value of the compTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompTypeId() {
        return compTypeId;
    }

    /**
     * Sets the value of the compTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompTypeId(BigInteger value) {
        this.compTypeId = value;
    }

    /**
     * Gets the value of the activeStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveStatusCode }
     *     
     */
    public ActiveStatusCode getActiveStatusCode() {
        return activeStatusCode;
    }

    /**
     * Sets the value of the activeStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveStatusCode }
     *     
     */
    public void setActiveStatusCode(ActiveStatusCode value) {
        this.activeStatusCode = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the sortTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortTitle() {
        return sortTitle;
    }

    /**
     * Sets the value of the sortTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortTitle(String value) {
        this.sortTitle = value;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * Sets the value of the subtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtitle(String value) {
        this.subtitle = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the parentalAdvisory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentalAdvisory() {
        return parentalAdvisory;
    }

    /**
     * Sets the value of the parentalAdvisory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentalAdvisory(String value) {
        this.parentalAdvisory = value;
    }

    /**
     * Gets the value of the isrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsrc() {
        return isrc;
    }

    /**
     * Sets the value of the isrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsrc(String value) {
        this.isrc = value;
    }

    /**
     * Gets the value of the itemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getItemNumber() {
        return itemNumber;
    }

    /**
     * Sets the value of the itemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setItemNumber(BigInteger value) {
        this.itemNumber = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpc() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpc(String value) {
        this.upc = value;
    }

    /**
     * Gets the value of the childItemsCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildItemsCount() {
        return childItemsCount;
    }

    /**
     * Sets the value of the childItemsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildItemsCount(BigInteger value) {
        this.childItemsCount = value;
    }

    /**
     * Gets the value of the coverArt property.
     * 
     * @return
     *     possible object is
     *     {@link TfIndicator }
     *     
     */
    public TfIndicator getCoverArt() {
        return coverArt;
    }

    /**
     * Sets the value of the coverArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TfIndicator }
     *     
     */
    public void setCoverArt(TfIndicator value) {
        this.coverArt = value;
    }

    /**
     * Gets the value of the single property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSingle() {
        return single;
    }

    /**
     * Sets the value of the single property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSingle(String value) {
        this.single = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the audioLanguages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getAudioLanguages() {
        return audioLanguages;
    }

    /**
     * Sets the value of the audioLanguages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setAudioLanguages(Languages value) {
        this.audioLanguages = value;
    }

    /**
     * Gets the value of the subtitleLanguages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getSubtitleLanguages() {
        return subtitleLanguages;
    }

    /**
     * Sets the value of the subtitleLanguages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setSubtitleLanguages(Languages value) {
        this.subtitleLanguages = value;
    }

    /**
     * Gets the value of the diskNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiskNumber() {
        return diskNumber;
    }

    /**
     * Sets the value of the diskNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiskNumber(BigInteger value) {
        this.diskNumber = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeason(String value) {
        this.season = value;
    }

    /**
     * Gets the value of the imprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprint() {
        return imprint;
    }

    /**
     * Sets the value of the imprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprint(String value) {
        this.imprint = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverage(String value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the tableOfContents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableOfContents() {
        return tableOfContents;
    }

    /**
     * Sets the value of the tableOfContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableOfContents(String value) {
        this.tableOfContents = value;
    }

    /**
     * Gets the value of the amgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmgId() {
        return amgId;
    }

    /**
     * Sets the value of the amgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmgId(String value) {
        this.amgId = value;
    }

    /**
     * Gets the value of the muzeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMuzeId() {
        return muzeId;
    }

    /**
     * Sets the value of the muzeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMuzeId(String value) {
        this.muzeId = value;
    }

    /**
     * Gets the value of the exclusiveInd property.
     * 
     * @return
     *     possible object is
     *     {@link TfIndicator }
     *     
     */
    public TfIndicator getExclusiveInd() {
        return exclusiveInd;
    }

    /**
     * Sets the value of the exclusiveInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TfIndicator }
     *     
     */
    public void setExclusiveInd(TfIndicator value) {
        this.exclusiveInd = value;
    }

    /**
     * Gets the value of the specialCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialCodes() {
        return specialCodes;
    }

    /**
     * Sets the value of the specialCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialCodes(String value) {
        this.specialCodes = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

}
