//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Counts-artist-comp-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Counts-artist-comp-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ARTIST" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ALBUM" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TRACK" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="COLLECTION" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MUSIC_VIDEO" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TV_SERIES" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TV_SHOW" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MOVIE" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="EBOOK" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="EB_TRACK" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Counts-artist-comp-type", propOrder = {
    "artist",
    "album",
    "track",
    "collection",
    "musicvideo",
    "tvseries",
    "tvshow",
    "movie",
    "ebook",
    "ebtrack"
})
public class CountsArtistCompType {

    @XmlElement(name = "ARTIST", required = true)
    protected BigInteger artist;
    @XmlElement(name = "ALBUM")
    protected BigInteger album;
    @XmlElement(name = "TRACK")
    protected BigInteger track;
    @XmlElement(name = "COLLECTION")
    protected BigInteger collection;
    @XmlElement(name = "MUSIC_VIDEO")
    protected BigInteger musicvideo;
    @XmlElement(name = "TV_SERIES")
    protected BigInteger tvseries;
    @XmlElement(name = "TV_SHOW")
    protected BigInteger tvshow;
    @XmlElement(name = "MOVIE")
    protected BigInteger movie;
    @XmlElement(name = "EBOOK")
    protected BigInteger ebook;
    @XmlElement(name = "EB_TRACK")
    protected BigInteger ebtrack;

    /**
     * Gets the value of the artist property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getARTIST() {
        return artist;
    }

    /**
     * Sets the value of the artist property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setARTIST(BigInteger value) {
        this.artist = value;
    }

    /**
     * Gets the value of the album property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getALBUM() {
        return album;
    }

    /**
     * Sets the value of the album property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setALBUM(BigInteger value) {
        this.album = value;
    }

    /**
     * Gets the value of the track property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTRACK() {
        return track;
    }

    /**
     * Sets the value of the track property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTRACK(BigInteger value) {
        this.track = value;
    }

    /**
     * Gets the value of the collection property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOLLECTION() {
        return collection;
    }

    /**
     * Sets the value of the collection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOLLECTION(BigInteger value) {
        this.collection = value;
    }

    /**
     * Gets the value of the musicvideo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMUSICVIDEO() {
        return musicvideo;
    }

    /**
     * Sets the value of the musicvideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMUSICVIDEO(BigInteger value) {
        this.musicvideo = value;
    }

    /**
     * Gets the value of the tvseries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTVSERIES() {
        return tvseries;
    }

    /**
     * Sets the value of the tvseries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTVSERIES(BigInteger value) {
        this.tvseries = value;
    }

    /**
     * Gets the value of the tvshow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTVSHOW() {
        return tvshow;
    }

    /**
     * Sets the value of the tvshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTVSHOW(BigInteger value) {
        this.tvshow = value;
    }

    /**
     * Gets the value of the movie property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMOVIE() {
        return movie;
    }

    /**
     * Sets the value of the movie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMOVIE(BigInteger value) {
        this.movie = value;
    }

    /**
     * Gets the value of the ebook property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEBOOK() {
        return ebook;
    }

    /**
     * Sets the value of the ebook property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEBOOK(BigInteger value) {
        this.ebook = value;
    }

    /**
     * Gets the value of the ebtrack property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEBTRACK() {
        return ebtrack;
    }

    /**
     * Sets the value of the ebtrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEBTRACK(BigInteger value) {
        this.ebtrack = value;
    }

}
