//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Feed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Feed">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}Header"/>
 *         &lt;element name="Statistics" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Total-label-owners" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Total-labels" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Total-components" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Total-components-by-type" type="{}Counts-by-comp-type"/>
 *                   &lt;element name="Total-artists" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Genre-Reference" type="{}Genre-Reference"/>
 *         &lt;element name="Component-Types" type="{}Component-Types"/>
 *         &lt;element name="Metadata-Types" type="{}Metadata-Types"/>
 *         &lt;element name="Metadata-Special-Codes" type="{}Metadata-Special-Codes"/>
 *         &lt;element name="Artist-Types" type="{}Artist-Types"/>
 *         &lt;element name="Territories" type="{}Territories"/>
 *         &lt;element name="Currencies" type="{}Currencies"/>
 *         &lt;element name="Price-Scopes" type="{}Price-Scopes"/>
 *         &lt;element name="Asset-Types" type="{}Asset-Types"/>
 *         &lt;element name="Collection-Assets-Map" type="{}Collection-Assets-Map"/>
 *         &lt;element name="Label-Owners" type="{}Label-Owners"/>
 *         &lt;element name="Labels" type="{}Labels"/>
 *         &lt;element name="Artists" type="{}Artists"/>
 *         &lt;element name="Components" type="{}Components"/>
 *         &lt;element name="Artist-Components" type="{}Artist-Components"/>
 *         &lt;element name="Artist-Metadata" type="{}Artist-Metadata"/>
 *         &lt;element name="Component-Parents" type="{}Component-Parents"/>
 *         &lt;element name="Metadata" type="{}Metadata"/>
 *         &lt;element name="Component-Actions" type="{}Component-Actions"/>
 *         &lt;element name="Wholesale-Prices" type="{}Wholesale-Prices" minOccurs="0"/>
 *         &lt;element name="Retail-Prices" type="{}Retail-Prices" minOccurs="0"/>
 *         &lt;element name="Media-Files" type="{}Media-Files" minOccurs="0"/>
 *         &lt;element name="Related-Components" type="{}Related-Components" minOccurs="0"/>
 *         &lt;element name="Alternate-Components" type="{}Alternate-Components" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Feed", propOrder = {
    "header",
    "statistics",
    "genreReference",
    "componentTypes",
    "metadataTypes",
    "metadataSpecialCodes",
    "artistTypes",
    "territories",
    "currencies",
    "priceScopes",
    "assetTypes",
    "collectionAssetsMap",
    "labelOwners",
    "labels",
    "artists",
    "components",
    "artistComponents",
    "artistMetadata",
    "componentParents",
    "metadata",
    "componentActions",
    "wholesalePrices",
    "retailPrices",
    "mediaFiles",
    "relatedComponents",
    "alternateComponents"
})
@XmlRootElement(name = "Feed")
public class Feed {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "Statistics")
    protected Feed.Statistics statistics;
    @XmlElement(name = "Genre-Reference", required = true)
    protected GenreReference genreReference;
    @XmlElement(name = "Component-Types", required = true)
    protected ComponentTypes componentTypes;
    @XmlElement(name = "Metadata-Types", required = true)
    protected MetadataTypes metadataTypes;
    @XmlElement(name = "Metadata-Special-Codes", required = true)
    protected MetadataSpecialCodes metadataSpecialCodes;
    @XmlElement(name = "Artist-Types", required = true)
    protected ArtistTypes artistTypes;
    @XmlElement(name = "Territories", required = true)
    protected Territories territories;
    @XmlElement(name = "Currencies", required = true)
    protected Currencies currencies;
    @XmlElement(name = "Price-Scopes", required = true)
    protected PriceScopes priceScopes;
    @XmlElement(name = "Asset-Types", required = true)
    protected AssetTypes assetTypes;
    @XmlElement(name = "Collection-Assets-Map", required = true)
    protected CollectionAssetsMap collectionAssetsMap;
    @XmlElement(name = "Label-Owners", required = true)
    protected LabelOwners labelOwners;
    @XmlElement(name = "Labels", required = true)
    protected Labels labels;
    @XmlElement(name = "Artists", required = true)
    protected Artists artists;
    @XmlElement(name = "Components", required = true)
    protected Components components;
    @XmlElement(name = "Artist-Components", required = true)
    protected ArtistComponents artistComponents;
    @XmlElement(name = "Artist-Metadata", required = true)
    protected ArtistMetadata artistMetadata;
    @XmlElement(name = "Component-Parents", required = true)
    protected ComponentParents componentParents;
    @XmlElement(name = "Metadata", required = true)
    protected Metadata metadata;
    @XmlElement(name = "Component-Actions", required = true)
    protected ComponentActions componentActions;
    @XmlElement(name = "Wholesale-Prices")
    protected WholesalePrices wholesalePrices;
    @XmlElement(name = "Retail-Prices")
    protected RetailPrices retailPrices;
    @XmlElement(name = "Media-Files")
    protected MediaFiles mediaFiles;
    @XmlElement(name = "Related-Components")
    protected RelatedComponents relatedComponents;
    @XmlElement(name = "Alternate-Components")
    protected AlternateComponents alternateComponents;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link Feed.Statistics }
     *     
     */
    public Feed.Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Feed.Statistics }
     *     
     */
    public void setStatistics(Feed.Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the genreReference property.
     * 
     * @return
     *     possible object is
     *     {@link GenreReference }
     *     
     */
    public GenreReference getGenreReference() {
        return genreReference;
    }

    /**
     * Sets the value of the genreReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenreReference }
     *     
     */
    public void setGenreReference(GenreReference value) {
        this.genreReference = value;
    }

    /**
     * Gets the value of the componentTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentTypes }
     *     
     */
    public ComponentTypes getComponentTypes() {
        return componentTypes;
    }

    /**
     * Sets the value of the componentTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentTypes }
     *     
     */
    public void setComponentTypes(ComponentTypes value) {
        this.componentTypes = value;
    }

    /**
     * Gets the value of the metadataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataTypes }
     *     
     */
    public MetadataTypes getMetadataTypes() {
        return metadataTypes;
    }

    /**
     * Sets the value of the metadataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataTypes }
     *     
     */
    public void setMetadataTypes(MetadataTypes value) {
        this.metadataTypes = value;
    }

    /**
     * Gets the value of the metadataSpecialCodes property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataSpecialCodes }
     *     
     */
    public MetadataSpecialCodes getMetadataSpecialCodes() {
        return metadataSpecialCodes;
    }

    /**
     * Sets the value of the metadataSpecialCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataSpecialCodes }
     *     
     */
    public void setMetadataSpecialCodes(MetadataSpecialCodes value) {
        this.metadataSpecialCodes = value;
    }

    /**
     * Gets the value of the artistTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ArtistTypes }
     *     
     */
    public ArtistTypes getArtistTypes() {
        return artistTypes;
    }

    /**
     * Sets the value of the artistTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtistTypes }
     *     
     */
    public void setArtistTypes(ArtistTypes value) {
        this.artistTypes = value;
    }

    /**
     * Gets the value of the territories property.
     * 
     * @return
     *     possible object is
     *     {@link Territories }
     *     
     */
    public Territories getTerritories() {
        return territories;
    }

    /**
     * Sets the value of the territories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Territories }
     *     
     */
    public void setTerritories(Territories value) {
        this.territories = value;
    }

    /**
     * Gets the value of the currencies property.
     * 
     * @return
     *     possible object is
     *     {@link Currencies }
     *     
     */
    public Currencies getCurrencies() {
        return currencies;
    }

    /**
     * Sets the value of the currencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currencies }
     *     
     */
    public void setCurrencies(Currencies value) {
        this.currencies = value;
    }

    /**
     * Gets the value of the priceScopes property.
     * 
     * @return
     *     possible object is
     *     {@link PriceScopes }
     *     
     */
    public PriceScopes getPriceScopes() {
        return priceScopes;
    }

    /**
     * Sets the value of the priceScopes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceScopes }
     *     
     */
    public void setPriceScopes(PriceScopes value) {
        this.priceScopes = value;
    }

    /**
     * Gets the value of the assetTypes property.
     * 
     * @return
     *     possible object is
     *     {@link AssetTypes }
     *     
     */
    public AssetTypes getAssetTypes() {
        return assetTypes;
    }

    /**
     * Sets the value of the assetTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetTypes }
     *     
     */
    public void setAssetTypes(AssetTypes value) {
        this.assetTypes = value;
    }

    /**
     * Gets the value of the collectionAssetsMap property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionAssetsMap }
     *     
     */
    public CollectionAssetsMap getCollectionAssetsMap() {
        return collectionAssetsMap;
    }

    /**
     * Sets the value of the collectionAssetsMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionAssetsMap }
     *     
     */
    public void setCollectionAssetsMap(CollectionAssetsMap value) {
        this.collectionAssetsMap = value;
    }

    /**
     * Gets the value of the labelOwners property.
     * 
     * @return
     *     possible object is
     *     {@link LabelOwners }
     *     
     */
    public LabelOwners getLabelOwners() {
        return labelOwners;
    }

    /**
     * Sets the value of the labelOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelOwners }
     *     
     */
    public void setLabelOwners(LabelOwners value) {
        this.labelOwners = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * @return
     *     possible object is
     *     {@link Labels }
     *     
     */
    public Labels getLabels() {
        return labels;
    }

    /**
     * Sets the value of the labels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labels }
     *     
     */
    public void setLabels(Labels value) {
        this.labels = value;
    }

    /**
     * Gets the value of the artists property.
     * 
     * @return
     *     possible object is
     *     {@link Artists }
     *     
     */
    public Artists getArtists() {
        return artists;
    }

    /**
     * Sets the value of the artists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Artists }
     *     
     */
    public void setArtists(Artists value) {
        this.artists = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link Components }
     *     
     */
    public Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link Components }
     *     
     */
    public void setComponents(Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the artistComponents property.
     * 
     * @return
     *     possible object is
     *     {@link ArtistComponents }
     *     
     */
    public ArtistComponents getArtistComponents() {
        return artistComponents;
    }

    /**
     * Sets the value of the artistComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtistComponents }
     *     
     */
    public void setArtistComponents(ArtistComponents value) {
        this.artistComponents = value;
    }

    /**
     * Gets the value of the artistMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ArtistMetadata }
     *     
     */
    public ArtistMetadata getArtistMetadata() {
        return artistMetadata;
    }

    /**
     * Sets the value of the artistMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtistMetadata }
     *     
     */
    public void setArtistMetadata(ArtistMetadata value) {
        this.artistMetadata = value;
    }

    /**
     * Gets the value of the componentParents property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentParents }
     *     
     */
    public ComponentParents getComponentParents() {
        return componentParents;
    }

    /**
     * Sets the value of the componentParents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentParents }
     *     
     */
    public void setComponentParents(ComponentParents value) {
        this.componentParents = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the componentActions property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentActions }
     *     
     */
    public ComponentActions getComponentActions() {
        return componentActions;
    }

    /**
     * Sets the value of the componentActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentActions }
     *     
     */
    public void setComponentActions(ComponentActions value) {
        this.componentActions = value;
    }

    /**
     * Gets the value of the wholesalePrices property.
     * 
     * @return
     *     possible object is
     *     {@link WholesalePrices }
     *     
     */
    public WholesalePrices getWholesalePrices() {
        return wholesalePrices;
    }

    /**
     * Sets the value of the wholesalePrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link WholesalePrices }
     *     
     */
    public void setWholesalePrices(WholesalePrices value) {
        this.wholesalePrices = value;
    }

    /**
     * Gets the value of the retailPrices property.
     * 
     * @return
     *     possible object is
     *     {@link RetailPrices }
     *     
     */
    public RetailPrices getRetailPrices() {
        return retailPrices;
    }

    /**
     * Sets the value of the retailPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetailPrices }
     *     
     */
    public void setRetailPrices(RetailPrices value) {
        this.retailPrices = value;
    }

    /**
     * Gets the value of the mediaFiles property.
     * 
     * @return
     *     possible object is
     *     {@link MediaFiles }
     *     
     */
    public MediaFiles getMediaFiles() {
        return mediaFiles;
    }

    /**
     * Sets the value of the mediaFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaFiles }
     *     
     */
    public void setMediaFiles(MediaFiles value) {
        this.mediaFiles = value;
    }

    /**
     * Gets the value of the relatedComponents property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedComponents }
     *     
     */
    public RelatedComponents getRelatedComponents() {
        return relatedComponents;
    }

    /**
     * Sets the value of the relatedComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedComponents }
     *     
     */
    public void setRelatedComponents(RelatedComponents value) {
        this.relatedComponents = value;
    }

    /**
     * Gets the value of the alternateComponents property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateComponents }
     *     
     */
    public AlternateComponents getAlternateComponents() {
        return alternateComponents;
    }

    /**
     * Sets the value of the alternateComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateComponents }
     *     
     */
    public void setAlternateComponents(AlternateComponents value) {
        this.alternateComponents = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Total-label-owners" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Total-labels" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Total-components" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Total-components-by-type" type="{}Counts-by-comp-type"/>
     *         &lt;element name="Total-artists" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalLabelOwners",
        "totalLabels",
        "totalComponents",
        "totalComponentsByType",
        "totalArtists"
    })
    public static class Statistics {

        @XmlElement(name = "Total-label-owners", required = true)
        protected BigInteger totalLabelOwners;
        @XmlElement(name = "Total-labels", required = true)
        protected BigInteger totalLabels;
        @XmlElement(name = "Total-components", required = true)
        protected BigInteger totalComponents;
        @XmlElement(name = "Total-components-by-type", required = true)
        protected CountsByCompType totalComponentsByType;
        @XmlElement(name = "Total-artists", required = true)
        protected BigInteger totalArtists;

        /**
         * Gets the value of the totalLabelOwners property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalLabelOwners() {
            return totalLabelOwners;
        }

        /**
         * Sets the value of the totalLabelOwners property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalLabelOwners(BigInteger value) {
            this.totalLabelOwners = value;
        }

        /**
         * Gets the value of the totalLabels property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalLabels() {
            return totalLabels;
        }

        /**
         * Sets the value of the totalLabels property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalLabels(BigInteger value) {
            this.totalLabels = value;
        }

        /**
         * Gets the value of the totalComponents property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalComponents() {
            return totalComponents;
        }

        /**
         * Sets the value of the totalComponents property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalComponents(BigInteger value) {
            this.totalComponents = value;
        }

        /**
         * Gets the value of the totalComponentsByType property.
         * 
         * @return
         *     possible object is
         *     {@link CountsByCompType }
         *     
         */
        public CountsByCompType getTotalComponentsByType() {
            return totalComponentsByType;
        }

        /**
         * Sets the value of the totalComponentsByType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CountsByCompType }
         *     
         */
        public void setTotalComponentsByType(CountsByCompType value) {
            this.totalComponentsByType = value;
        }

        /**
         * Gets the value of the totalArtists property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalArtists() {
            return totalArtists;
        }

        /**
         * Sets the value of the totalArtists property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalArtists(BigInteger value) {
            this.totalArtists = value;
        }

    }

}
