//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Metadata-stats complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Metadata-stats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ISRC" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TrackNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DiskNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UPC" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ParentalAdvisory" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ReleaseDate" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="AmgId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="MuzeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Metadata-stats", propOrder = {
    "isrc",
    "trackNumber",
    "diskNumber",
    "upc",
    "parentalAdvisory",
    "releaseDate",
    "amgId",
    "muzeId"
})
public class MetadataStats {

    @XmlElement(name = "ISRC", required = true)
    protected BigInteger isrc;
    @XmlElement(name = "TrackNumber", required = true)
    protected BigInteger trackNumber;
    @XmlElement(name = "DiskNumber", required = true)
    protected BigInteger diskNumber;
    @XmlElement(name = "UPC", required = true)
    protected BigInteger upc;
    @XmlElement(name = "ParentalAdvisory", required = true)
    protected BigInteger parentalAdvisory;
    @XmlElement(name = "ReleaseDate", required = true)
    protected BigInteger releaseDate;
    @XmlElement(name = "AmgId", required = true)
    protected BigInteger amgId;
    @XmlElement(name = "MuzeId", required = true)
    protected BigInteger muzeId;

    /**
     * Gets the value of the isrc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getISRC() {
        return isrc;
    }

    /**
     * Sets the value of the isrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setISRC(BigInteger value) {
        this.isrc = value;
    }

    /**
     * Gets the value of the trackNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrackNumber() {
        return trackNumber;
    }

    /**
     * Sets the value of the trackNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrackNumber(BigInteger value) {
        this.trackNumber = value;
    }

    /**
     * Gets the value of the diskNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiskNumber() {
        return diskNumber;
    }

    /**
     * Sets the value of the diskNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiskNumber(BigInteger value) {
        this.diskNumber = value;
    }

    /**
     * Gets the value of the upc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUPC() {
        return upc;
    }

    /**
     * Sets the value of the upc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUPC(BigInteger value) {
        this.upc = value;
    }

    /**
     * Gets the value of the parentalAdvisory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentalAdvisory() {
        return parentalAdvisory;
    }

    /**
     * Sets the value of the parentalAdvisory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentalAdvisory(BigInteger value) {
        this.parentalAdvisory = value;
    }

    /**
     * Gets the value of the releaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReleaseDate() {
        return releaseDate;
    }

    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReleaseDate(BigInteger value) {
        this.releaseDate = value;
    }

    /**
     * Gets the value of the amgId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAmgId() {
        return amgId;
    }

    /**
     * Sets the value of the amgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAmgId(BigInteger value) {
        this.amgId = value;
    }

    /**
     * Gets the value of the muzeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMuzeId() {
        return muzeId;
    }

    /**
     * Sets the value of the muzeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMuzeId(BigInteger value) {
        this.muzeId = value;
    }

}
