//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amanotes.music.xsd.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ActionsByAssetA360_QNAME = new QName("", "a360");
    private final static QName _ActionsByAssetA440_QNAME = new QName("", "a440");
    private final static QName _ActionsByAssetA324_QNAME = new QName("", "a324");
    private final static QName _ActionsByAssetA049_QNAME = new QName("", "a049");
    private final static QName _ActionsByAssetA522_QNAME = new QName("", "a522");
    private final static QName _ActionsByAssetA403_QNAME = new QName("", "a403");
    private final static QName _ActionsByAssetA404_QNAME = new QName("", "a404");
    private final static QName _ActionsByAssetA800_QNAME = new QName("", "a800");
    private final static QName _ActionsByAssetA320_QNAME = new QName("", "a320");
    private final static QName _ActionsByAssetA443_QNAME = new QName("", "a443");
    private final static QName _ActionsByAssetA520_QNAME = new QName("", "a520");
    private final static QName _ActionsByAssetA400_QNAME = new QName("", "a400");
    private final static QName _ActionsByAssetA521_QNAME = new QName("", "a521");
    private final static QName _ActionsByAssetA074_QNAME = new QName("", "a074");
    private final static QName _ActionsByAssetA350_QNAME = new QName("", "a350");
    private final static QName _ActionsByAssetA075_QNAME = new QName("", "a075");
    private final static QName _ActionsByAssetA076_QNAME = new QName("", "a076");
    private final static QName _ActionsByAssetA110_QNAME = new QName("", "a110");
    private final static QName _ActionsByAssetA077_QNAME = new QName("", "a077");
    private final static QName _ActionsByAssetA070_QNAME = new QName("", "a070");
    private final static QName _ActionsByAssetA30X_QNAME = new QName("", "a30X");
    private final static QName _ActionsByAssetA434_QNAME = new QName("", "a434");
    private final static QName _ActionsByAssetA511_QNAME = new QName("", "a511");
    private final static QName _ActionsByAssetA512_QNAME = new QName("", "a512");
    private final static QName _ActionsByAssetA430_QNAME = new QName("", "a430");
    private final static QName _ActionsByAssetA310_QNAME = new QName("", "a310");
    private final static QName _ActionsByAssetA113_QNAME = new QName("", "a113");
    private final static QName _ActionsByAssetA433_QNAME = new QName("", "a433");
    private final static QName _ActionsByAssetA510_QNAME = new QName("", "a510");
    private final static QName _ActionsByAssetA020_QNAME = new QName("", "a020");
    private final static QName _ActionsByAssetA460_QNAME = new QName("", "a460");
    private final static QName _ActionsByAssetA340_QNAME = new QName("", "a340");
    private final static QName _ActionsByAssetA504_QNAME = new QName("", "a504");
    private final static QName _ActionsByAssetA423_QNAME = new QName("", "a423");
    private final static QName _ActionsByAssetA104_QNAME = new QName("", "a104");
    private final static QName _ActionsByAssetA500_QNAME = new QName("", "a500");
    private final static QName _ActionsByAssetA303_QNAME = new QName("", "a303");
    private final static QName _ActionsByAssetA501_QNAME = new QName("", "a501");
    private final static QName _ActionsByAssetA029_QNAME = new QName("", "a029");
    private final static QName _ActionsByAssetA502_QNAME = new QName("", "a502");
    private final static QName _ActionsByAssetA503_QNAME = new QName("", "a503");
    private final static QName _ActionsByAssetA980_QNAME = new QName("", "a980");
    private final static QName _ActionsByAssetA463_QNAME = new QName("", "a463");
    private final static QName _ActionsByAssetA023_QNAME = new QName("", "a023");
    private final static QName _ActionsByAssetA100_QNAME = new QName("", "a100");
    private final static QName _ActionsByAssetA981_QNAME = new QName("", "a981");
    private final static QName _ActionsByAssetA420_QNAME = new QName("", "a420");
    private final static QName _ActionsByAssetA024_QNAME = new QName("", "a024");
    private final static QName _ActionsByAssetA300_QNAME = new QName("", "a300");
    private final static QName _ActionsByAssetA103_QNAME = new QName("", "a103");
    private final static QName _ActionsByAssetA450_QNAME = new QName("", "a450");
    private final static QName _ActionsByAssetA010_QNAME = new QName("", "a010");
    private final static QName _ActionsByAssetA330_QNAME = new QName("", "a330");
    private final static QName _ActionsByAssetA374_QNAME = new QName("", "a374");
    private final static QName _ActionsByAssetA090_QNAME = new QName("", "a090");
    private final static QName _ActionsByAssetA40Z_QNAME = new QName("", "a40Z");
    private final static QName _ActionsByAssetA40W_QNAME = new QName("", "a40W");
    private final static QName _ActionsByAssetA40X_QNAME = new QName("", "a40X");
    private final static QName _ActionsByAssetA017_QNAME = new QName("", "a017");
    private final static QName _ActionsByAssetA413_QNAME = new QName("", "a413");
    private final static QName _ActionsByAssetA019_QNAME = new QName("", "a019");
    private final static QName _ActionsByAssetA453_QNAME = new QName("", "a453");
    private final static QName _ActionsByAssetA014_QNAME = new QName("", "a014");
    private final static QName _ActionsByAssetA454_QNAME = new QName("", "a454");
    private final static QName _ActionsByAssetA410_QNAME = new QName("", "a410");
    private final static QName _ActionsByAssetA334_QNAME = new QName("", "a334");
    private final static QName _ActionsByAssetA015_QNAME = new QName("", "a015");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amanotes.music.xsd.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RelatedComponents }
     * 
     */
    public RelatedComponents createRelatedComponents() {
        return new RelatedComponents();
    }

    /**
     * Create an instance of {@link CountsArtistCompType }
     * 
     */
    public CountsArtistCompType createCountsArtistCompType() {
        return new CountsArtistCompType();
    }

    /**
     * Create an instance of {@link Artist }
     * 
     */
    public Artist createArtist() {
        return new Artist();
    }

    /**
     * Create an instance of {@link GenreReference }
     * 
     */
    public GenreReference createGenreReference() {
        return new GenreReference();
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Languages }
     * 
     */
    public Languages createLanguages() {
        return new Languages();
    }

    /**
     * Create an instance of {@link AltGroup }
     * 
     */
    public AltGroup createAltGroup() {
        return new AltGroup();
    }

    /**
     * Create an instance of {@link RelatedComponent }
     * 
     */
    public RelatedComponent createRelatedComponent() {
        return new RelatedComponent();
    }

    /**
     * Create an instance of {@link TerritoryData }
     * 
     */
    public TerritoryData createTerritoryData() {
        return new TerritoryData();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Territories }
     * 
     */
    public Territories createTerritories() {
        return new Territories();
    }

    /**
     * Create an instance of {@link Territory }
     * 
     */
    public Territory createTerritory() {
        return new Territory();
    }

    /**
     * Create an instance of {@link Genre }
     * 
     */
    public Genre createGenre() {
        return new Genre();
    }

    /**
     * Create an instance of {@link AlternateComponents }
     * 
     */
    public AlternateComponents createAlternateComponents() {
        return new AlternateComponents();
    }

    /**
     * Create an instance of {@link ArtistTypes }
     * 
     */
    public ArtistTypes createArtistTypes() {
        return new ArtistTypes();
    }

    /**
     * Create an instance of {@link Currencies }
     * 
     */
    public Currencies createCurrencies() {
        return new Currencies();
    }

    /**
     * Create an instance of {@link PriceScope }
     * 
     */
    public PriceScope createPriceScope() {
        return new PriceScope();
    }

    /**
     * Create an instance of {@link LabelOwner }
     * 
     */
    public LabelOwner createLabelOwner() {
        return new LabelOwner();
    }

    /**
     * Create an instance of {@link ComponentActions }
     * 
     */
    public ComponentActions createComponentActions() {
        return new ComponentActions();
    }

    /**
     * Create an instance of {@link ComponentAction }
     * 
     */
    public ComponentAction createComponentAction() {
        return new ComponentAction();
    }

    /**
     * Create an instance of {@link MetadataSpecialCodes }
     * 
     */
    public MetadataSpecialCodes createMetadataSpecialCodes() {
        return new MetadataSpecialCodes();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link CountsByCompType }
     * 
     */
    public CountsByCompType createCountsByCompType() {
        return new CountsByCompType();
    }

    /**
     * Create an instance of {@link Feed.Statistics }
     * 
     */
    public Feed.Statistics createFeedStatistics() {
        return new Feed.Statistics();
    }

    /**
     * Create an instance of {@link RetailPrice }
     * 
     */
    public RetailPrice createRetailPrice() {
        return new RetailPrice();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link PriceScopes }
     * 
     */
    public PriceScopes createPriceScopes() {
        return new PriceScopes();
    }

    /**
     * Create an instance of {@link AssetType }
     * 
     */
    public AssetType createAssetType() {
        return new AssetType();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link CollectionAssetsMap }
     * 
     */
    public CollectionAssetsMap createCollectionAssetsMap() {
        return new CollectionAssetsMap();
    }

    /**
     * Create an instance of {@link ArtistComponent }
     * 
     */
    public ArtistComponent createArtistComponent() {
        return new ArtistComponent();
    }

    /**
     * Create an instance of {@link ActionsByAsset }
     * 
     */
    public ActionsByAsset createActionsByAsset() {
        return new ActionsByAsset();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link LabelOwners }
     * 
     */
    public LabelOwners createLabelOwners() {
        return new LabelOwners();
    }

    /**
     * Create an instance of {@link Artists }
     * 
     */
    public Artists createArtists() {
        return new Artists();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link RetailPrices }
     * 
     */
    public RetailPrices createRetailPrices() {
        return new RetailPrices();
    }

    /**
     * Create an instance of {@link ArtistComponents }
     * 
     */
    public ArtistComponents createArtistComponents() {
        return new ArtistComponents();
    }

    /**
     * Create an instance of {@link ArtistMetadata }
     * 
     */
    public ArtistMetadata createArtistMetadata() {
        return new ArtistMetadata();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Labels }
     * 
     */
    public Labels createLabels() {
        return new Labels();
    }

    /**
     * Create an instance of {@link ArtistType }
     * 
     */
    public ArtistType createArtistType() {
        return new ArtistType();
    }

    /**
     * Create an instance of {@link ComponentParent }
     * 
     */
    public ComponentParent createComponentParent() {
        return new ComponentParent();
    }

    /**
     * Create an instance of {@link CamItem }
     * 
     */
    public CamItem createCamItem() {
        return new CamItem();
    }

    /**
     * Create an instance of {@link SpecialCode }
     * 
     */
    public SpecialCode createSpecialCode() {
        return new SpecialCode();
    }

    /**
     * Create an instance of {@link WholesalePrices }
     * 
     */
    public WholesalePrices createWholesalePrices() {
        return new WholesalePrices();
    }

    /**
     * Create an instance of {@link MetadataStats }
     * 
     */
    public MetadataStats createMetadataStats() {
        return new MetadataStats();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link AssetTypes }
     * 
     */
    public AssetTypes createAssetTypes() {
        return new AssetTypes();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link ComponentParents }
     * 
     */
    public ComponentParents createComponentParents() {
        return new ComponentParents();
    }

    /**
     * Create an instance of {@link ComponentTypes }
     * 
     */
    public ComponentTypes createComponentTypes() {
        return new ComponentTypes();
    }

    /**
     * Create an instance of {@link MetadataTypes }
     * 
     */
    public MetadataTypes createMetadataTypes() {
        return new MetadataTypes();
    }

    /**
     * Create an instance of {@link WholesalePrice }
     * 
     */
    public WholesalePrice createWholesalePrice() {
        return new WholesalePrice();
    }

    /**
     * Create an instance of {@link ArtistMetadataItem }
     * 
     */
    public ArtistMetadataItem createArtistMetadataItem() {
        return new ArtistMetadataItem();
    }

    /**
     * Create an instance of {@link MediaFiles }
     * 
     */
    public MediaFiles createMediaFiles() {
        return new MediaFiles();
    }

    /**
     * Create an instance of {@link MetadataItem }
     * 
     */
    public MetadataItem createMetadataItem() {
        return new MetadataItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a360", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA360(String value) {
        return new JAXBElement<String>(_ActionsByAssetA360_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a440", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA440(String value) {
        return new JAXBElement<String>(_ActionsByAssetA440_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a324", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA324(String value) {
        return new JAXBElement<String>(_ActionsByAssetA324_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a049", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA049(String value) {
        return new JAXBElement<String>(_ActionsByAssetA049_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a522", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA522(String value) {
        return new JAXBElement<String>(_ActionsByAssetA522_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a403", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA403(String value) {
        return new JAXBElement<String>(_ActionsByAssetA403_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a404", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA404(String value) {
        return new JAXBElement<String>(_ActionsByAssetA404_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a800", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA800(String value) {
        return new JAXBElement<String>(_ActionsByAssetA800_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a320", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA320(String value) {
        return new JAXBElement<String>(_ActionsByAssetA320_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a443", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA443(String value) {
        return new JAXBElement<String>(_ActionsByAssetA443_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a520", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA520(String value) {
        return new JAXBElement<String>(_ActionsByAssetA520_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a400", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA400(String value) {
        return new JAXBElement<String>(_ActionsByAssetA400_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a521", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA521(String value) {
        return new JAXBElement<String>(_ActionsByAssetA521_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a074", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA074(String value) {
        return new JAXBElement<String>(_ActionsByAssetA074_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a350", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA350(String value) {
        return new JAXBElement<String>(_ActionsByAssetA350_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a075", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA075(String value) {
        return new JAXBElement<String>(_ActionsByAssetA075_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a076", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA076(String value) {
        return new JAXBElement<String>(_ActionsByAssetA076_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a110", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA110(String value) {
        return new JAXBElement<String>(_ActionsByAssetA110_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a077", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA077(String value) {
        return new JAXBElement<String>(_ActionsByAssetA077_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a070", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA070(String value) {
        return new JAXBElement<String>(_ActionsByAssetA070_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a30X", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA30X(String value) {
        return new JAXBElement<String>(_ActionsByAssetA30X_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a434", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA434(String value) {
        return new JAXBElement<String>(_ActionsByAssetA434_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a511", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA511(String value) {
        return new JAXBElement<String>(_ActionsByAssetA511_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a512", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA512(String value) {
        return new JAXBElement<String>(_ActionsByAssetA512_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a430", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA430(String value) {
        return new JAXBElement<String>(_ActionsByAssetA430_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a310", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA310(String value) {
        return new JAXBElement<String>(_ActionsByAssetA310_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a113", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA113(String value) {
        return new JAXBElement<String>(_ActionsByAssetA113_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a433", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA433(String value) {
        return new JAXBElement<String>(_ActionsByAssetA433_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a510", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA510(String value) {
        return new JAXBElement<String>(_ActionsByAssetA510_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a020", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA020(String value) {
        return new JAXBElement<String>(_ActionsByAssetA020_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a460", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA460(String value) {
        return new JAXBElement<String>(_ActionsByAssetA460_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a340", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA340(String value) {
        return new JAXBElement<String>(_ActionsByAssetA340_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a504", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA504(String value) {
        return new JAXBElement<String>(_ActionsByAssetA504_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a423", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA423(String value) {
        return new JAXBElement<String>(_ActionsByAssetA423_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a104", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA104(String value) {
        return new JAXBElement<String>(_ActionsByAssetA104_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a500", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA500(String value) {
        return new JAXBElement<String>(_ActionsByAssetA500_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a303", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA303(String value) {
        return new JAXBElement<String>(_ActionsByAssetA303_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a501", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA501(String value) {
        return new JAXBElement<String>(_ActionsByAssetA501_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a029", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA029(String value) {
        return new JAXBElement<String>(_ActionsByAssetA029_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a502", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA502(String value) {
        return new JAXBElement<String>(_ActionsByAssetA502_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a503", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA503(String value) {
        return new JAXBElement<String>(_ActionsByAssetA503_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a980", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA980(String value) {
        return new JAXBElement<String>(_ActionsByAssetA980_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a463", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA463(String value) {
        return new JAXBElement<String>(_ActionsByAssetA463_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a023", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA023(String value) {
        return new JAXBElement<String>(_ActionsByAssetA023_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a100", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA100(String value) {
        return new JAXBElement<String>(_ActionsByAssetA100_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a981", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA981(String value) {
        return new JAXBElement<String>(_ActionsByAssetA981_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a420", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA420(String value) {
        return new JAXBElement<String>(_ActionsByAssetA420_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a024", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA024(String value) {
        return new JAXBElement<String>(_ActionsByAssetA024_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a300", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA300(String value) {
        return new JAXBElement<String>(_ActionsByAssetA300_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a103", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA103(String value) {
        return new JAXBElement<String>(_ActionsByAssetA103_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a450", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA450(String value) {
        return new JAXBElement<String>(_ActionsByAssetA450_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a010", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA010(String value) {
        return new JAXBElement<String>(_ActionsByAssetA010_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a330", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA330(String value) {
        return new JAXBElement<String>(_ActionsByAssetA330_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a374", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA374(String value) {
        return new JAXBElement<String>(_ActionsByAssetA374_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a090", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA090(String value) {
        return new JAXBElement<String>(_ActionsByAssetA090_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a40Z", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA40Z(String value) {
        return new JAXBElement<String>(_ActionsByAssetA40Z_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a40W", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA40W(String value) {
        return new JAXBElement<String>(_ActionsByAssetA40W_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a40X", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA40X(String value) {
        return new JAXBElement<String>(_ActionsByAssetA40X_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a017", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA017(String value) {
        return new JAXBElement<String>(_ActionsByAssetA017_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a413", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA413(String value) {
        return new JAXBElement<String>(_ActionsByAssetA413_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a019", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA019(String value) {
        return new JAXBElement<String>(_ActionsByAssetA019_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a453", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA453(String value) {
        return new JAXBElement<String>(_ActionsByAssetA453_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a014", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA014(String value) {
        return new JAXBElement<String>(_ActionsByAssetA014_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a454", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA454(String value) {
        return new JAXBElement<String>(_ActionsByAssetA454_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a410", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA410(String value) {
        return new JAXBElement<String>(_ActionsByAssetA410_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a334", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA334(String value) {
        return new JAXBElement<String>(_ActionsByAssetA334_QNAME, String.class, ActionsByAsset.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a015", scope = ActionsByAsset.class)
    public JAXBElement<String> createActionsByAssetA015(String value) {
        return new JAXBElement<String>(_ActionsByAssetA015_QNAME, String.class, ActionsByAsset.class, value);
    }

}
