//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.14 at 10:05:49 AM ICT 
//


package com.amanotes.music.xsd.model.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Wholesale-Price complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Wholesale-Price">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Comp-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Price-Scope-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Territory-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Currency-Id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="Price-Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *             &lt;choice>
 *               &lt;element name="Required-Retail-Price" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *               &lt;element name="Sugg-Retail-Price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *             &lt;/choice>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="Required-Retail-Price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Effective-From-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Effective-To-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Created-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Last-Updated-Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Wholesale-Price", propOrder = {
    "compId",
    "priceScopeId",
    "territoryId",
    "currencyId",
    "priceAmount",
    "suggRetailPrice",
    "requiredRetailPrice",
    "effectiveFromDate",
    "effectiveToDate",
    "createdDate",
    "lastUpdatedDate"
})
public class WholesalePrice {

    @XmlElement(name = "Comp-Id", required = true)
    protected BigInteger compId;
    @XmlElement(name = "Price-Scope-Id", required = true)
    protected BigInteger priceScopeId;
    @XmlElement(name = "Territory-Id", required = true)
    protected BigInteger territoryId;
    @XmlElement(name = "Currency-Id", required = true)
    protected BigInteger currencyId;
    @XmlElement(name = "Price-Amount")
    protected Float priceAmount;
    @XmlElement(name = "Sugg-Retail-Price")
    protected Float suggRetailPrice;
    @XmlElement(name = "Required-Retail-Price")
    protected Float requiredRetailPrice;
    @XmlElement(name = "Effective-From-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveFromDate;
    @XmlElement(name = "Effective-To-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveToDate;
    @XmlElement(name = "Created-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "Last-Updated-Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdatedDate;

    /**
     * Gets the value of the compId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompId() {
        return compId;
    }

    /**
     * Sets the value of the compId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompId(BigInteger value) {
        this.compId = value;
    }

    /**
     * Gets the value of the priceScopeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriceScopeId() {
        return priceScopeId;
    }

    /**
     * Sets the value of the priceScopeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriceScopeId(BigInteger value) {
        this.priceScopeId = value;
    }

    /**
     * Gets the value of the territoryId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTerritoryId() {
        return territoryId;
    }

    /**
     * Sets the value of the territoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTerritoryId(BigInteger value) {
        this.territoryId = value;
    }

    /**
     * Gets the value of the currencyId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurrencyId() {
        return currencyId;
    }

    /**
     * Sets the value of the currencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurrencyId(BigInteger value) {
        this.currencyId = value;
    }

    /**
     * Gets the value of the priceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPriceAmount() {
        return priceAmount;
    }

    /**
     * Sets the value of the priceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPriceAmount(Float value) {
        this.priceAmount = value;
    }

    /**
     * Gets the value of the suggRetailPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSuggRetailPrice() {
        return suggRetailPrice;
    }

    /**
     * Sets the value of the suggRetailPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSuggRetailPrice(Float value) {
        this.suggRetailPrice = value;
    }

    /**
     * Gets the value of the requiredRetailPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRequiredRetailPrice() {
        return requiredRetailPrice;
    }

    /**
     * Sets the value of the requiredRetailPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRequiredRetailPrice(Float value) {
        this.requiredRetailPrice = value;
    }

    /**
     * Gets the value of the effectiveFromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveFromDate() {
        return effectiveFromDate;
    }

    /**
     * Sets the value of the effectiveFromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveFromDate(XMLGregorianCalendar value) {
        this.effectiveFromDate = value;
    }

    /**
     * Gets the value of the effectiveToDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveToDate() {
        return effectiveToDate;
    }

    /**
     * Sets the value of the effectiveToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveToDate(XMLGregorianCalendar value) {
        this.effectiveToDate = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDate(XMLGregorianCalendar value) {
        this.lastUpdatedDate = value;
    }

}
